### ISSUE TITLE
Agregar imagenes en el carrousel

### ISSUE THREAD

**Issue by crfimdoivj** [HelgaZambrana/java_CodoACodo#9]
Las imagenes ya estan en la carpeta /public/images.
Las imagenes a implementar tiene como prefijo carrousel. Solo son tres imagenes

![image](https://github.com/HelgaZambrana/java_CodoACodo/assets/69734513/ab025216-0e30-466d-92df-71e56a3947b4)

**Comment by HelgaZambrana** [comment]
Lo tomo.

**Comment by crfimdoivj** [comment]
Helga, Ramito completo esta tarea. Si queres te asigno la ultima issue que queda. Igual hasta que  haga la PR no voy a cerrar la issue
